# Generated by Django 4.2.10 on 2024-05-19 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaVO",
            fields=[
                (
                    "area_id",
                    models.AutoField(
                        db_column="area_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "area_name",
                    models.CharField(db_column="area_name", default="", max_length=255),
                ),
                ("area_code", models.IntegerField(db_column="area_code")),
            ],
            options={"db_table": "area_table",},
        ),
        migrations.CreateModel(
            name="CategoryVO",
            fields=[
                (
                    "category_id",
                    models.AutoField(
                        db_column="category_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "category_image",
                    models.ImageField(
                        blank=True,
                        db_column="category_image",
                        null=True,
                        upload_to="static/adminResources/categoryImage/",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        db_column="category_name", default="", max_length=255
                    ),
                ),
                (
                    "category_description",
                    models.TextField(
                        db_column="category_description", default="", max_length=255
                    ),
                ),
            ],
            options={"db_table": "category_table",},
        ),
        migrations.CreateModel(
            name="ComplainVO",
            fields=[
                (
                    "complain_id",
                    models.AutoField(
                        db_column="complain_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "complain_subject",
                    models.CharField(
                        db_column="complain_subject", default="", max_length=255
                    ),
                ),
                (
                    "complain_description",
                    models.TextField(
                        db_column="complain_description", default="", max_length=500
                    ),
                ),
                ("complain_date", models.DateField(db_column="complain_date")),
                (
                    "complain_status",
                    models.CharField(
                        db_column="complain_status", default="", max_length=255
                    ),
                ),
            ],
            options={"db_table": "complain_table",},
        ),
        migrations.CreateModel(
            name="LoginVO",
            fields=[
                (
                    "login_id",
                    models.AutoField(
                        db_column="login_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "login_username",
                    models.CharField(
                        db_column="login_username", default="", max_length=200
                    ),
                ),
                (
                    "login_password",
                    models.CharField(
                        db_column="login_password", default="", max_length=200
                    ),
                ),
                (
                    "login_role",
                    models.CharField(db_column="login_role", default="", max_length=10),
                ),
                (
                    "login_status",
                    models.BooleanField(
                        db_column="login_status", default="", max_length=1
                    ),
                ),
            ],
            options={"db_table": "login_table",},
        ),
        migrations.CreateModel(
            name="UserVO",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        db_column="user_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "user_firstname",
                    models.CharField(
                        db_column="user_firstname", default="", max_length=200
                    ),
                ),
                (
                    "user_lastname",
                    models.CharField(
                        db_column="user_lastname", default="", max_length=200
                    ),
                ),
                (
                    "user_gender",
                    models.CharField(
                        db_column="user_gender", default="", max_length=10
                    ),
                ),
                (
                    "user_address",
                    models.CharField(
                        db_column="user_address", default="", max_length=200
                    ),
                ),
                (
                    "user_area_vo",
                    models.ForeignKey(
                        db_column="user_area_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.areavo",
                    ),
                ),
                (
                    "user_login_vo",
                    models.ForeignKey(
                        db_column="user_login_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.loginvo",
                    ),
                ),
            ],
            options={"db_table": "register_table",},
        ),
        migrations.CreateModel(
            name="SubCategoryVO",
            fields=[
                (
                    "subcategory_id",
                    models.AutoField(
                        db_column="subcategory_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "subcategory_image",
                    models.ImageField(
                        blank=True,
                        db_column="subcategory_image",
                        null=True,
                        upload_to="static/adminResources/subcategoryImage/",
                    ),
                ),
                (
                    "subcategory_name",
                    models.CharField(
                        db_column="subcategory_name", default="", max_length=255
                    ),
                ),
                (
                    "subcategory_description",
                    models.TextField(
                        db_column="subcategory_description", default="", max_length=255
                    ),
                ),
                (
                    "subcategory_category_vo",
                    models.ForeignKey(
                        db_column="subcategory_category_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.categoryvo",
                    ),
                ),
            ],
            options={"db_table": "subcategory_table",},
        ),
        migrations.CreateModel(
            name="ReplyVO",
            fields=[
                (
                    "reply_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="reply_id"
                    ),
                ),
                (
                    "reply_description",
                    models.TextField(
                        default="", max_length=500, verbose_name="reply_description"
                    ),
                ),
                (
                    "reply_datetime",
                    models.DateTimeField(db_column="reply_datetime", default=""),
                ),
                (
                    "reply_complain_vo",
                    models.ForeignKey(
                        db_column="reply_complain_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.complainvo",
                    ),
                ),
                (
                    "reply_login_vo",
                    models.ForeignKey(
                        db_column="reply_login_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.loginvo",
                    ),
                ),
            ],
            options={"db_table": "reply_table",},
        ),
        migrations.CreateModel(
            name="ProductVO",
            fields=[
                (
                    "product_id",
                    models.AutoField(
                        db_column="product_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        db_column="product_name", default="", max_length=50
                    ),
                ),
                (
                    "product_description",
                    models.TextField(
                        db_column="product_description", default="", max_length=500
                    ),
                ),
                ("product_quantity", models.IntegerField(db_column="product_quantity")),
                ("product_price", models.IntegerField(db_column="product_price")),
                (
                    "product_color",
                    models.CharField(
                        db_column="product_color", default="", max_length=100
                    ),
                ),
                (
                    "product_adjustable",
                    models.CharField(
                        db_column="product_adjustable", default="", max_length=100
                    ),
                ),
                (
                    "product_material",
                    models.CharField(
                        db_column="product_material", default="", max_length=100
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(
                        db_column="product_image",
                        upload_to="static/adminResources/product/",
                    ),
                ),
                (
                    "product_category_id",
                    models.ForeignKey(
                        db_column="product_category_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.categoryvo",
                    ),
                ),
                (
                    "product_subcategory_id",
                    models.ForeignKey(
                        db_column="product_subcategory_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.subcategoryvo",
                    ),
                ),
            ],
            options={"db_table": "product_table",},
        ),
        migrations.CreateModel(
            name="OrderVO",
            fields=[
                (
                    "order_id",
                    models.AutoField(
                        db_column="order_id", primary_key=True, serialize=False
                    ),
                ),
                ("order_date", models.DateField(db_column="order_date")),
                (
                    "order_delivery_date",
                    models.DateField(db_column="order_delivery_date"),
                ),
                (
                    "order_status",
                    models.CharField(
                        db_column="order_status", default="", max_length=255, null=True
                    ),
                ),
                (
                    "order_quantity",
                    models.IntegerField(db_column="order_quantity", default=""),
                ),
                (
                    "order_total",
                    models.IntegerField(db_column="order_total", default=""),
                ),
                (
                    "order_invoice",
                    models.IntegerField(db_column="order_invoice", default=""),
                ),
                (
                    "order_product_vo",
                    models.ForeignKey(
                        db_column="order_product_id",
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.productvo",
                    ),
                ),
                (
                    "order_user_vo",
                    models.ForeignKey(
                        db_column="order_user_id",
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.uservo",
                    ),
                ),
            ],
            options={"db_table": "order_table",},
        ),
        migrations.CreateModel(
            name="DeviceInfoVO",
            fields=[
                (
                    "device_id",
                    models.AutoField(
                        db_column="device_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "device_identity",
                    models.TextField(
                        db_column="device_identity", default="", max_length=500
                    ),
                ),
                (
                    "device_login_vo",
                    models.ForeignKey(
                        db_column="device_login_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.loginvo",
                    ),
                ),
            ],
            options={"db_table": "device_info_table",},
        ),
        migrations.AddField(
            model_name="complainvo",
            name="complain_user_vo",
            field=models.ForeignKey(
                db_column="complain_user_id",
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="base.uservo",
            ),
        ),
        migrations.CreateModel(
            name="CartVO",
            fields=[
                (
                    "cart_id",
                    models.AutoField(
                        db_column="cart_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "cart_quantity",
                    models.IntegerField(db_column="cart_quantity", default=""),
                ),
                (
                    "cart_subtotal",
                    models.IntegerField(db_column="cart_subtotal", default=""),
                ),
                (
                    "cart_product_vo",
                    models.ForeignKey(
                        db_column="cart_product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.productvo",
                    ),
                ),
                (
                    "cart_user_vo",
                    models.ForeignKey(
                        db_column="cart_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.uservo",
                    ),
                ),
            ],
            options={"db_table": "cart_table",},
        ),
    ]
