from django.urls import path

from . import (area_view, category_view, subcategory_view, \
               product_view, \
               cart_view, order_view, complain_view, feedback_view, login_view,
               user_view, index_user_view)

urlpatterns = [
    path('', login_view.admin_load_login, name="admin_load_login"),
    path('admin_validate_login', login_view.admin_validate_login,
         name="admin_validate_login"),
    path('admin_load_dashboard', login_view.admin_load_dashboard,
         name="admin_load_dashboard"),

    path('admin_logout_session', login_view.admin_logout_session,
         name="admin_logout_session"),
    path('user_validate_login_username',
         login_view.user_validate_login_username,
         name="user_validate_login_username"),
    path('admin_block_user', login_view.admin_block_user,
         name="admin_block_user"),
    path('admin_unblock_user', login_view.admin_unblock_user,
         name="admin_unblock_user"),

    path('admin_add_category', category_view.admin_add_category,
         name='admin_add_category'),
    path('admin_insert_category', category_view.admin_insert_category,
         name='admin_insert_category'),
    path('admin_view_category', category_view.admin_view_category,
         name='admin_view_category'),
    path('admin_delete_category', category_view.admin_delete_category,
         name="admin_delete_category"),
    path('admin_edit_category', category_view.admin_edit_category,
         name="admin_edit_category"),
    path('admin_update_category', category_view.admin_update_category,
         name="admin_update_category"),

    path('admin_load_subcategory', subcategory_view.admin_load_subcategory,
         name="admin_load_subcategory"),
    path('admin_insert_subcategory', subcategory_view.admin_insert_subcategory,
         name="admin_insert_subcategory"),
    path('admin_view_subcategory', subcategory_view.admin_view_subcategory,
         name="admin_view_subcategory"),
    path('admin_delete_subcategory', subcategory_view.admin_delete_subcategory,
         name="admin_delete_subcategory"),
    path('admin_edit_subcategory', subcategory_view.admin_edit_subcategory,
         name="admin_edit_subcategory"),
    path('admin_update_subcategory', subcategory_view.admin_update_subcategory,
         name="admin_update_subcategory"),

    path('admin_add_product', product_view.admin_add_product,
         name='admin_add_product'),
    path('ajax_subcategory_product', product_view.ajax_subcategory_product,
         name='ajax_subcategory_product'),
    path('admin_insert_product', product_view.admin_insert_product,
         name='admin_insert_product'),
    path('admin_view_product', product_view.admin_view_product,
         name='admin_view_product'),
    path('admin_delete_product', product_view.admin_delete_product,
         name='admin_delete_product'),
    path('admin_edit_product', product_view.admin_edit_product,
         name='admin_edit_product'),
    path('admin_update_product', product_view.admin_update_product,
         name='admin_update_product'),
    # path('admin_edit_image_product', product_view.admin_edit_image_product,
    #      name='admin_edit_image_product'),
    # path('admin_update_image_product', product_view.admin_update_image_product,
    #      name='admin_update_image_product'),

    path('admin_view_cart', cart_view.admin_view_cart, name='admin_view_cart'),
    path('admin_view_order', order_view.admin_view_order,
         name='admin_view_order'),
    path('admin_view_complain', complain_view.admin_view_complain,
         name='admin_view_complain'),
    path('admin_reply_complain/', complain_view.admin_reply_complain,
         name="admin_reply_complain"),
    path('admin_view_feedback', feedback_view.admin_view_feedback,
         name='admin_view_feedback'),

    path('admin_add_area', area_view.admin_add_area, name='admin_add_area'),
    path('admin_insert_area', area_view.admin_insert_area,
         name='admin_insert_area'),
    path('admin_view_area', area_view.admin_view_area, name='admin_view_area'),
    path('admin_delete_area', area_view.admin_delete_area,
         name='admin_delete_area'),
    path('admin_edit_area', area_view.admin_edit_area, name='admin_edit_area'),
    path('admin_update_area', area_view.admin_update_area,
         name='admin_update_area'),

    # <! ----------------------User template---------------------- !>

    path('user_logout/', login_view.user_logout,
         name="user_logout"),

    path('user_load_register', user_view.user_load_register,
         name="user_load_register"),
    path('user_insert_register', user_view.user_insert_register,
         name="user_insert_register"),
    path('admin_view_user', user_view.admin_view_user,
         name="admin_view_user"),

    path('user_load_dashboard', login_view.user_load_dashboard,
         name="user_load_dashboard"),

    path('user_load_category', category_view.user_load_category,
         name="user_load_category"),
    path('user_category', category_view.user_category,
         name="user_category"),

    path('user_load_subcategory', subcategory_view.user_load_subcategory,
         name='user_load_subcategory'),
    path('user_subcategory', subcategory_view.user_subcategory,
         name="user_subcategory"),

    path('user_load_product', product_view.user_load_product,
         name="user_load_product"),
    path('user_details_product', product_view.user_details_product,
         name="user_details_product"),
    path('user_products', product_view.user_products, name="user_products"),
    path('user_product', product_view.user_product,
         name='user_product'),

    path('user_order', order_view.user_order, name="user_order"),
    path('user_cart/', order_view.user_cart,
         name='user_cart'),
    path('user_insert_cart/', order_view.user_insert_cart,
         name='user_insert_cart'),
    path('user_delete_cart/', order_view.user_delete_cart,
         name='user_delete_cart'),
    path('user_edit_cart/', order_view.user_edit_cart,
         name='user_edit_cart'),
    path('user_update_cart/', order_view.user_update_cart,
         name='user_update_product'),
    path('user_insert_order/', order_view.user_insert_order,
         name='user_insert_order'),
    path('user_view_order/', order_view.user_view_order,
         name='user_view_order'),
    path('user_delete_order/', order_view.user_delete_order,
         name="user_delete_order"),

    path('user_contact_us/', complain_view.user_contact_us,
         name='user_contact_us'),
    path('user_send_complain/', complain_view.user_send_complain,
         name='user_send_complain'),
    path('admin_insert_complain_reply/',
         complain_view.admin_insert_complain_reply,
         name='admin_insert_complain_reply'),

    path('user_load_home', index_user_view.user_load_home,
         name='user_load_home'),
    path('user_thankyou', index_user_view.user_thankyou, name='user_thankyou'),
    path('user_about', index_user_view.user_about, name="user_about"),
    path('user_price', index_user_view.user_price,
         name='user_price'),
    path('user_invoice', index_user_view.user_invoice,
         name='user_invoice'),
]
